version: '3'

services:
  api:
    image: api
    build:
      context: ./back/
      args:
        ENV_FILE: ${ENV_FILE}
    env_file: ./back/${ENV_FILE}
    command: "gunicorn wsgi -b :8000"
    ports:
      - "5004:8000"

  front:
    image: front
    build:
      context: ./front/
    ports:
      - "5005:80"

