networks:
    qnetwork:

services:
    pgsql:
        image: postgres:12-alpine
        environment:
            - POSTGRES_DB=extract
            - POSTGRES_USER=extractuser
            - POSTGRES_PASSWORD=demopassword
        ports:
            - "5432:5432"

    extract:
        build: ./extract
        container_name: extract
        depends_on:
            pgsql:
                condition: service_started
        environment:
            - JAVA_OPTS=-Xms1G -Xmx2G -Duser.language=fr -Duser.region=CH -Dcom.sun.jndi.ldap.connect.pool.timeout=20000
        ports:
            - "8080:8080"
        healthcheck:
            test: curl --fail http://localhost:8080/extract || exit 1
            interval: 10s
            timeout: 10s
            retries: 15
