networks:
    qnetwork:

services:

    # Extract 
    extract:
        build: ./extract
        depends_on:
            pgsql:
                condition: service_healthy
            geodata:
                condition: service_healthy                
        environment: 
            - JAVA_OPTS=-Xms1G -Xmx2G 
              -Dspring.datasource.url="jdbc:postgresql://pgsql:5432/extract" 
              -Dspring.datasource.username=extractuser 
              -Dspring.datasource.password=demopassword 
              -Duser.language=en -Duser.region=CH -Dcom.sun.jndi.ldap.connect.pool.timeout=20000
            - GEODATA_POSTGRES_HOST=geodata
            - GEODATA_POSTGRES_DB=geodata
            - GEODATA_POSTGRES_USER=extractuser
            - GEODATA_POSTGRES_PASSWORD=demopassword
        ports:
            - "8080:8080"
        healthcheck:
            test: curl --fail http://localhost:8080/extract || exit 1
            interval: 10s
            timeout: 10s
            retries: 15

    # Extract/Postgres
    pgsql:
        image: postgres:12-alpine
        environment:
            - POSTGRES_DB=extract
            - POSTGRES_USER=extractuser
            - POSTGRES_PASSWORD=demopassword
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U extractuser -d postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

    # Extract/Postgis
    geodata:
        image: postgis/postgis:12-3.4-alpine
        environment:
            - POSTGRES_DB=geodata
            - POSTGRES_USER=extractuser
            - POSTGRES_PASSWORD=demopassword
        ports:
            - "54320:5432"
        volumes:
          - ./extract/geodata:/docker-entrypoint-initdb.d/
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U extractuser -d postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

    # Extract/Updatedb
    updatedb:
        image: postgres:12-alpine
        depends_on:
            extract:
                condition: service_healthy
        environment:
            - PGHOST=pgsql
            - PGDB=extract
            - PGUSER=extractuser
            - PGPASSWORD=demopassword
        volumes:
            - ./updatedb:/updatedb
        entrypoint: /updatedb/update.sh

    # Geoshop
    geoshop:
        build: ./geoshop
        depends_on: 
            postgis:
                condition: service_healthy
        environment:
            - POSTGRES_HOST=postgis
            - POSTGRES_USER=geoshop
            - POSTGRES_DB=geoshop
            - POSTGRES_PASSWORD=geoshop
        ports: 
            - "8000:8000"
        healthcheck:
            test: curl --fail http://localhost:8000 || exit 1
            interval: 10s
            timeout: 10s
            retries: 15       

    # Geoshop/Postgis
    postgis:
        image: postgis/postgis:12-3.4-alpine
        environment:
            - POSTGRES_DB=geoshop
            - POSTGRES_USER=geoshop
            - POSTGRES_PASSWORD=geoshop
        volumes:
          - ./geoshop/postgis:/docker-entrypoint-initdb.d/
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U geoshop"]
            interval: 5s
            timeout: 5s
            retries: 5

    # Mailhog
    mailhog:
        image: mailhog/mailhog
        tty: true
        ports:
            - "1025:1025"
            - "8025:8025"
        volumes:
            - ./mailhog:/home/mailhog/conf
        entrypoint: MailHog -auth-file=/home/mailhog/conf/auth-users

    # LDAP
    openldap:
        image: osixia/openldap:1.5.0
        environment:
            - LDAP_ORGANISATION=Extract
            - LDAP_DOMAIN=extract.org
            - LDAP_ADMIN_PASSWORD=extract
            - LDAP_CONFIG_PASSWORD=extract
            - LDAP_RFC2307BIS_SCHEMA=true
            - LDAP_REMOVE_CONFIG_AFTER_SETUP=true
            - LDAP_TLS_VERIFY_CLIENT=try
        ports:
            - "389:389"
            - "636:636"

    ldap-ad:
        build: ./ldap-ad
        volumes:
            - ./ldap-ad/users.ldif:/ldap/users.ldif
        ports:
            - "10389:10389"

    # QGIS
    qgisserver:
        image: camptocamp/qgis-server
        volumes:
            - ./qgis/project:/etc/qgisserver
        environment:
            - QGIS_PROJECT_FILE=/etc/qgisserver/world.qgs
            - QGIS_SERVER_LANDING_PAGE_PROJECTS_DIRECTORIES=/etc/qgisserver
        networks:
            - qnetwork

    qgisproxy:
        depends_on:
            qgisserver:
                condition: service_started
        build:
            context: ./qgis
        hostname: qgisproxy
        container_name: qgisproxy
        volumes:
            - ./qgis/nginx.conf:/etc/nginx/nginx/conf:ro
        ports:
            - 8888:80
        networks:
            - qnetwork
            - default