networks:
    qnetwork:

services:
    pgsql:
        image: postgres:12-alpine
        environment:
            - POSTGRES_DB=extract
            - POSTGRES_USER=extractuser
            - POSTGRES_PASSWORD=demopassword
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

    updatedb:
        build: ./updatedb
        depends_on:
            pgsql:
                condition: service_healthy
        environment:
            - PGHOST=pgsql
            - PGDB=extract
            - PGUSER=extractuser
            - PGPASSWORD=demopassword

    extract:
        build: ./extract
        depends_on:
            updatedb:
                condition: service_completed_successfully
        environment:
            - JAVA_OPTS=-Xms1G -Xmx2G -Duser.language=fr -Duser.region=CH -Dcom.sun.jndi.ldap.connect.pool.timeout=20000
        ports:
            - "8080:8080"
        healthcheck:
            test: curl --fail http://localhost:8080/extract || exit 1
            interval: 10s
            timeout: 10s
            retries: 15