version: '3'

services:
  api:
    image: api
    build:
      context: ./back/
    env_file: ./back/.env
    command: "gunicorn wsgi -b :8000"
    ports:
      - "5004:8000"

  front:
    image: front
    build:
      context: ./front/
    ports:
      - "5005:80"
    volumes:
      - ./logs:/usr/local/apache2/logs
